### ISSUE TITLE
Rewrite for AJS

### ISSUE THREAD

**Issue by JamesPHoughton** [JamesPHoughton/interdependent-diffusion#28]
Example papers:
- Bruch, Elizabeth E. 2014. “How Population Structure Shapes Neighborhood Segregation.” AJS; American Journal of Sociology 119 (5): 1221–78.
- DellaPosta, Daniel, Yongren Shi, and Michael Macy. 2015. “Why Do Liberals Drink Lattes?” The American Journal of Sociology 120 (5): 1473–1511.
- Centola, Damon. 2015. “The Social Origins of Networks and Diffusion.” The American Journal of Sociology 120 (5): 1295–1338.

## Todo:
- [ ] Update Fig 1
- [ ] Update Fig 2
- [ ] Update Fig 3
- [ ] Update Fig 4
- [ ] Update Fig 5

#### Text
Readable copy for the purposes of peer review is 
- [ ] set in a serif typeface (e.g., Times Roman) 
- [ ] at a font no smaller than 11 points (we prefer 12). 
- [ ] Manuscript text should be double spaced 
- [ ] with margins of at least one inch all around the page. 
In addition to the main text, every submission must include 
- [ ] (1) an abstract, 
- [ ] (2) a reference list, and 
- [ ] any (3) notes, 
- [ ] (4) tables, or 
- [ ] (5) figures mentioned in the text. 
- [ ] A word count that includes text, notes, and references must be included in the cover letter. 
- [ ] While AJS does not have any word-count limit, we encourage authors to be as concise as possible. Authors should note that referees may request more time to read papers over 16,000 words. 
- [ ] Please organize your paper so that the elements are gathered in this order: abstract, text, references, notes (if using endnotes rather than footnotes), figures, and tables. If your paper places figures and tables where they are discussed in the text rather than at the back of the manuscript, the AJS editorial board may decline to read it.

#### Abstract
- [ ] Your abstract should be as close to 100 words as possible. 
- [ ] It should include your research question or puzzle, 
- [ ] identify your data, and 
- [ ] give some indication of your findings. 
- [ ] Your abstract is likely to be sent by email to potential readers: giving an accurate and efficient statement of your project is likely to increase your chances of enlisting their aid. Unfocused, verbose abstracts may make it harder to place your paper with referees. Papers without an abstract cannot be sent to readers for peer review.

#### References
- [ ] AJS uses the author/date style of references, but it also allows notes for substantive commentary (see below). Papers without a reference list cannot be sent to readers for peer review.
- [ ] Please be sure that your reference list is arranged in alphabetical order and that a comma precedes “and” in three-author works.
- [ ] Every citation in the text or substantive notes must have a corresponding reference entry, and every publication listed in the reference list must be mentioned in the text or notes.
- [ ] AJS prefers that web pages be referred to in notes rather than in the reference list. This allows authors to explain their use of the source, including date accessed.
- [ ] For citations of works with three authors, AJS prints all the names at first appearance in text, but uses first author’s last name plus “et al.” thereafter. Citations of works by more than three authors will appear as first author’s last name plus “et al.” at all occurrences.
- [ ] AJS requests that authors supply inclusive page numbers for book chapters.
In the reference list, we prefer complete author names (i.e., Bearman, Peter, James Moody, and Kate Stovel, not Bearman, P., J. Moody, and K. Stovel).
- [ ] Please use headline style capitalization (capitalize all words except articles, coordinating conjunctions, and prepositions) and enclose article titles and book chapter titles in quotation marks. Please note that AJS uses the comma following the first, reversed name in a pair of authors:
Fernandez, Roberto, and Roger Gould. 1994. “A Dilemma of State Power: Brokerage and Influence in the National Health Policy Domain.” American Journal of Sociology 99 (6): 1455–91.

#### Notes
The first note (an acknowledgment note) should appear on the cover sheet of the manuscript. For the purposes of peer review, please mark this note with an asterisk and start your note numbering with “1” in the main text of the manuscript, with your substantive notes. Either footnotes or endnotes are acceptable.

#### Tables
Tables should be numbered consecutively as they appear in text. AJS strongly prefers that authors number discrete items separately (table 1, 2, 3, 4, etc.) as opposed to grouping items together (tables 1, table 2a, 2b, 2c).
- [ ] Appendix tables are numbered table A1, A2, or table B1, B2, and so on. AJS frowns on the use of font in tables (i.e., bold or italic to mark a specific cell) and avoids the use of “panel” to refer to a specific group of table entries. 
- [ ] AJS requires that you collect tables together at the back of your manuscript; do not place them where cited in the text.

### Figures
- [ ] As is the case for tables, number figures consecutively. 
- [ ] Select your typeface carefully: thick or very ornate letters and numbers can be difficult to read; likewise, san serif characters may be too thin for clarity. Check copy for overlapping or misspelled words. 
- [ ] If your paper is accepted for publication, your figure will have to fit on a 26 by 42 pica surface, so it may be helpful to keep that size in mind as you create your initial artwork.
- [ ] AJS does not print color figures. Online-only content may include color in supplemental figures.
Generally, images will be crisper if you use text fill rather than gray scale for your figures.

#### Submission
- [ ] You may submit your paper as a single electronic file, including all of your tables and figures, or you may submit several files (text, tables, figures). 
- [ ] You will be required to submit a cover page separately from the manuscript so that your personal information is not part of the manuscript file.
- [ ] Although you will be asked to paste your abstract into a text window early in the process, you must still retain a copy of the abstract in the paper you submit.
- [ ] Although Editorial Manager accepts PDF files and LaTeX files, we will have the greatest flexibility in working with your paper if you assemble your file in Word. Before sending papers to readers, AJS adds a serial number and a confidentiality stamp to your manuscript, and these alterations are very time consuming and sometimes unsuccessful in PDF or LaTeX.
If you are submitting a revised paper, don’t forget to include your revision memo (and remember, this must not reveal your identity to the referees).
- [ ] New submissions require a submission fee of $30. The AJS editorial office will contact authors with payment information. Graduate students submitting as sole authors are not required to pay this fee, but proof of status may be requested.

# Todos:
- [ ] Ask editor for example papers with simulation + theory building + experiment
- [ ] Check the voice "we" vs. "I"
